export const experience = [
    {
        id: 'DAT',
        title: 'Full-Stack TypeScript Developer',
        company: 'Dealer Automation Technologies',
        date: 'Jun 2023 - Present',
        place: 'Miami, Florida, United States · Hybrid',
        description:
            'Full-Stack Developer skilled in both front-end and back-end development, and with a strong use of AWS. My main job is to use MongoDB, GraphQL, React, and Node.js, alongside Amazon Web Services (AWS), to create, build, and launch modern serverless web applications.',
    },
    {
        id: 'HEXAWARE',
        title: 'Senior Software Engineer',
        company: 'Hexaware Technologies · Full-time',
        date: 'Jul 2021 - Jun 2023',
        place: 'Guadalajara, Jalisco, Mexico · Remote',
        description:
            'Senior Software Engineer of a data exchange application (DEx) using TypeScript, ReactJS, and Office JavaScript API (Office.js). The DEx is an Excel add-in platform for managing taxes where users can share data between different workbooks. As a senior software engineer, I handled and processed a large number of data on the client side and improved the performance of the application. Developed and implemented new features using Clean Code principles and best practices.',
    },
    {
        id: 'NEXXTWAY',
        title: 'Full-Stack JavaScript Developer',
        company: 'Nexxtway · Freelance',
        date: 'Apr 2020 - Jul 2021',
        place: 'Guadalajara, Jalisco, Mexico · Remote',
        description:
            'Specialized in front-end development using JavaScript, ReactJS, and Styled Components, and backend development using Node.js and MongoDB. Conducted unit and integration tests using Jest, and Cypress. Implemented and maintained Function Store, a marketplace of Google Cloud Functions, and EverTransit products which is a leading-edge fleet management tool. Worked on developing and maintaining React-rainbow-components and Rainbow-modules which are open-source React libraries.',
    },
    {
        id: 'ETECSA',
        title: 'Full-Stack Java Developer',
        company: 'ETECSA · Full-time',
        date: 'Sep 2016 - Dec 2018',
        place: 'Havana, Cuba · On-site',
        description:
            'Specialized in web development and database administration using a variety of languages and technologies. HTML5, CSS3, JavaScript, and JQuery for the front-end development, Java, Spring Boot for the backend development, and PostgreSQL for the database. Developed the TelPub web application that allowed the ETECSA employees to manage the data generated by the Public Telephone department and increased company efficiency and productivity by 80%.',
    },
];
