export const projects = [
    {
        id: 'Ever-Transit',
        type: 'main',
        tech: "EverTransit is a leading-edge fleet management tool. It helps you manage your fleet cheaper, faster, and easier with the industry's most advanced technology.",
        alt: 'EverTransit',
        img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1659927415/portfolio/P_EverTransit_cv7v8v.jpg',
        url: 'https://www.evertransit.com',
    },
    {
        id: 'Functions-Store',
        type: 'main',
        tech: 'Functions-Store is a marketplace of Google Cloud Functions. Developers can install and configure Cloud Functions with a click of a button.',
        alt: 'Functions-Store',
        img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1622564268/portfolio/P_FunctionsStore_g6xjwc.jpg',
        url: 'https://app.functions.store',
    },
    {
        id: 'Paquete-IO',
        type: 'main',
        tech: 'paquete.io is a solution that helps simplify the package management process in buildings.',
        alt: 'paquete.io',
        img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1659927415/portfolio/P_PaqueteIO_hthwsv.jpg',
        url: 'https://paquete.io',
    },
    {
        id: 'Rainbow-Modules',
        type: 'main',
        tech: 'Rainbow-Modules includes a collection of components, fully integrated with Firebase, that will help you to build apps.',
        alt: 'Rainbow-Modules',
        img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1615837557/portfolio/P_RainbowModules_vyl7dv.jpg',
        url: 'https://rainbow-modules.web.app/?path=/story/introduction-getting-started-overview--page',
        github: 'https://github.com/nexxtway/rainbow-modules',
    },
    {
        id: 'React-Rainbow-Components',
        type: 'main',
        tech: 'React-Rainbow-Components is an open-source project, with a collection of components that will help you build your application in a faster way.',
        alt: 'React-Rainbow-Components',
        img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1615837254/portfolio/P_ReactRainbow_ka03y9.jpg',
        url: 'https://react-rainbow.io/#/GettingStarted',
        github: 'https://github.com/nexxtway/react-rainbow',
    },
    {
        id: 'Pizza-App',
        type: 'practice',
        tech: 'TypeScript, React, React Router DOM v6, React Query, Context API, Formik, Styled Components, Java, Spring Boot, MySQL, Heroku, Netlify',
        alt: 'Pizza App',
        img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1673213200/portfolio/P_PizzaApp_qfc7vd.jpg',
        url: 'https://spring-pizza-store.netlify.app/',
        github: 'https://github.com/amontalvof/springboot-pizza-client',
        fontSize: '14px',
    },
    {
        id: 'TULOGO-E-commerce',
        type: 'practice',
        tech: 'TypeScript, React, Redux, React Query, JWT, Formik, Styled Components, Bootstrap, Node, Express, MySQL, Railway, Netlify',
        alt: 'TULOGO E-commerce',
        img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1659925838/portfolio/P_TULOGO_sonn0d.jpg',
        url: 'https://tulogo-ecommerce.netlify.app/',
        github: 'https://github.com/amontalvof/ts-frontend-ecommerce',
        fontSize: '14px',
    },
    {
        id: 'Effortless-React',
        type: 'practice',
        tech: 'TypeScript, React, Storybook, Styled Components, Github Pages',
        alt: 'Effortless React',
        img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1654528817/portfolio/P_EffortlessReact_vcajgb.jpg',
        url: 'https://amontalvof.github.io/effortless-react/',
        github: 'https://github.com/amontalvof/effortless-react',
        fontSize: '16px',
    },
    // {
    //     id: 'Calculator-App',
    //     type: 'practice',
    //     tech: 'HTML5, CSS3, TypeScript, Webpack, Github Pages',
    //     alt: 'Calculator App',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1641155119/portfolio/P_Calculator_hkor8m.jpg',
    //     url: 'https://amontalvof.github.io/typescript-calculator/',
    //     github: 'https://github.com/amontalvof/typescript-calculator',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'MinesWeeper-Game',
    //     type: 'practice',
    //     tech: 'HTML5, CSS3, TypeScript, Webpack, Github Pages',
    //     alt: 'MinesWeeper Game',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1641064940/portfolio/P_MinesWeeper_lqp5qt.jpg',
    //     url: 'https://amontalvof.github.io/typescript-minesweeper/',
    //     github: 'https://github.com/amontalvof/typescript-minesweeper',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'Calendar-App',
    //     type: 'practice',
    //     tech: 'React, Redux, Node.js, Express.js, MongoDB, Bootstrap, Cyclic',
    //     alt: 'Calendar App',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1613772859/portfolio/P_CalendarApp_cfgqjl.jpg',
    //     url: 'https://drab-pear-basket-clam-cuff.cyclic.app/',
    //     github: 'https://github.com/amontalvof/react-calendar-app',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'Todo-List',
    //     type: 'practice',
    //     tech: 'Todo List Template, JavaScript, Webpack, Github Pages',
    //     alt: 'Todo List App',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1612070206/portfolio/P_TodoList_cck1qv.jpg',
    //     url: 'https://amontalvof.github.io/javascript-todo-list/',
    //     github: 'https://github.com/amontalvof/javascript-todo-list',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'BLackjack-Game',
    //     type: 'practice',
    //     tech: 'HTML5, CSS3, JavaScript, Bootstrap, Github Pages',
    //     alt: 'BLackjack Game',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1612070175/portfolio/P_BlackJack_zqvbtg.jpg',
    //     url: 'https://amontalvof.github.io/javascript-blackjack/',
    //     github: 'https://github.com/amontalvof/javascript-blackjack',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'Journal-App',
    //     type: 'practice',
    //     tech: 'React, Redux, Sass, Firebase, Firestore',
    //     alt: 'Journal App',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1612070175/portfolio/P_JournalApp_yozmrq.jpg',
    //     url: 'https://react-journal-app-b6735.web.app/',
    //     github: 'https://github.com/amontalvof/react-journal-app',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'Airbnb-Clone',
    //     type: 'practice',
    //     tech: 'React, CSS3, Material UI, Firebase',
    //     alt: 'Airbnb Clone',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1612070175/portfolio/P_AirBnbClone_uywa6o.jpg',
    //     url: 'https://react-airbnb-clone-67a8a.web.app/',
    //     github: 'https://github.com/amontalvof/react-airbnb-clone',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'Netflix-Clone',
    //     type: 'practice',
    //     tech: 'React, CSS3, Firebase',
    //     alt: 'Netflix Clone',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1612070175/portfolio/P_NetflixClone_jncm99.jpg',
    //     url: 'https://react-netflix-clone-4b7e3.web.app/',
    //     github: 'https://github.com/amontalvof/react-netflix-clone',
    // },
    // {
    //     id: 'Antique-Tech-Store',
    //     type: 'practice',
    //     tech: 'React, Styled Components, Netlify, React Rainbow Components',
    //     alt: 'Antique Tech Store',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1612070175/portfolio/P_AntiqueTechStore_tsxhqd.jpg',
    //     url: 'https://am-react-antique-tech-store.netlify.app',
    //     github: 'https://github.com/amontalvof/react-antique-tech-store',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'Technology-Store',
    //     type: 'practice',
    //     tech: 'React, Styled Components, Netlify, React Rainbow Components',
    //     alt: 'Technology Store',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1612070175/portfolio/P_TechnologyStore_whuh1c.jpg',
    //     url: 'https://am-react-technology-store.netlify.app',
    //     github: 'https://github.com/amontalvof/react-technology-store',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'Beach-Resort',
    //     type: 'practice',
    //     tech: 'React, CSS3, Netlify',
    //     alt: 'Beach Resort',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1612075973/portfolio/P_BeachResort_rysray.jpg',
    //     url: 'https://am-react-resort.netlify.app',
    //     github: 'https://github.com/amontalvof/react-beach-resort',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'Global-Superstore',
    //     type: 'practice',
    //     tech: 'Java, Spring Boot, Thymeleaf, Docker, Render',
    //     alt: 'Global Superstore',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1667448954/portfolio/P_GlobalSuperstore_zina5z.jpg',
    //     url: 'https://springboot-global-superstore.onrender.com',
    //     github: 'https://github.com/amontalvof/springboot-global-superstore',
    //     fontSize: '16px',
    // },
    // {
    //     id: 'Phone-Ecommerce',
    //     type: 'practice',
    //     tech: 'React, Bootstrap, Netlify',
    //     alt: 'Phone Ecommerce Store',
    //     img: 'https://res.cloudinary.com/a03m02f92/image/upload/v1612075537/portfolio/P_PhoneEcommerce_syuvrq.jpg',
    //     url: 'https://am-react-phone-ecommerce.netlify.app',
    //     github: 'https://github.com/amontalvof/react-phone-ecommerce',
    //     fontSize: '16px',
    // },
];
