import { renderSimpleIcon } from 'react-icon-cloud';
import type { SimpleIcon } from 'simple-icons';
import {
    siHtml5,
    siCss3,
    siSass,
    siJavascript,
    siTypescript,
    siGraphql,
    siStyledcomponents,
    siReact,
    siReactquery,
    siReacthookform,
    siReactrouter,
    siRedux,
    siStorybook,
    siBootstrap,
    siNodedotjs,
    siNestjs,
    siExpress,
    siJest,
    siCypress,
    siGithub,
    siGit,
    siPostman,
    siVisualstudiocode,
    siSpringboot,
    siPython,
    siJsonwebtokens,
    siSocketdotio,
    siMongodb,
    siMysql,
    siRedis,
    siAwslambda,
    siFirebase,
    siDocker,
    siBitbucket,
    siHeroku,
} from 'simple-icons';
import { DARK_BLUE } from '../constants/colors';

const resolveIcons = () => {
    return [
        siHtml5,
        siCss3,
        siSass,
        siJavascript,
        siTypescript,
        siGraphql,
        siStyledcomponents,
        siReact,
        siReactquery,
        siReacthookform,
        siReactrouter,
        siRedux,
        siStorybook,
        siBootstrap,
        siNodedotjs,
        siNestjs,
        siExpress,
        siJest,
        siCypress,
        siGithub,
        siGit,
        siPostman,
        siVisualstudiocode,
        siSpringboot,
        siPython,
        siJsonwebtokens,
        siSocketdotio,
        siMongodb,
        siMysql,
        siRedis,
        siAwslambda,
        siFirebase,
        siDocker,
        siBitbucket,
        siHeroku,
    ].map((icon: SimpleIcon) => {
        return renderSimpleIcon({
            icon,
            minContrastRatio: 2,
            bgHex: DARK_BLUE,
            size: 40,
            aProps: {
                onClick: (e: any) => e.preventDefault(),
            },
        });
    });
};

export default resolveIcons;
